[program:online-quiz-queue]
command=php /var/www/online_quiz_system/artisan queue:work database --queue=default --sleep=1 --tries=3 --timeout=120
directory=/var/www/online_quiz_system
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/online-quiz-queue.log
stopwaitsecs=3600
