[program:online-quiz-reverb]
command=php /var/www/online_quiz_system/artisan reverb:start --host=0.0.0.0 --port=8080
directory=/var/www/online_quiz_system
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/online-quiz-reverb.log
stopwaitsecs=3600
